### PR TITLE
State Linux is the preferred dev platform in readme

### PR DESCRIPTION
**Pull request by swift502**
I just went through a loop of trying to build on Windows (got errors), then WSL (got errors) and finally an Ubuntu VM (so far seems to work). Others also seemed to have had issues building on Windows (#1121).

Supposing most contributors build on Linux, this line in readme would've saved me a lot of time, googling and frustration.

Just an idea, feel free to decline.
Have a nice day.

### CODE REVIEW

**Comment by swift502** [comment]
@googlebot I signed it!

**Comment by elalish** [comment]
Sorry about the lack of windows support; I just got a windows laptop, so I'm hoping to finally resolve this dev hurdle. MacOS is fine; that's what I develop on. Did you close this because you got it working?

**Comment by swift502** [comment]
@elalish I closed this because WSL might actually be fine, I probably just had na outdated node or npm version on there and that caused errors.

The Windows build didn't work though and I don't know the cause. So I guess it's good to include the message for the time being.

**Comment by elalish** [comment]
Yes, I believe someone else also found that WSL had an out of date node version by default. Now that I have a windows machine to test on I'll try to get it working better and update the docs accordingly.

**Pull request closed without merging**
