### PR TITLE
Scroll gating

### LINKED ISSUE #1424: Turning off scroll listener?
### Description

Is it possible to turn off only the scrolling listener from the model viewer, but keeping the drag controls on? I have the model viewer expanded on full page width. When a user scrolls down he can't process on the page because he got stuck in the model zooming. In general is it possible to turn off the zooming? 

#### Live Demo
http://sterman.g3kunden.de/produkte/spindelbaugruppen

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

### Versions

- model-viewer: v1.1.0
- three.js: r0.117.1

### PR DESCRIPTION
**Pull request by elalish**
Fixes #1424 

This change makes vertical touch gestures into scroll events instead of orbit. You have to start by moving side-to-side in order to trigger orbit mode. This makes pages with model-viewer elements (like our examples pages) much easier to navigate on mobile, as these elements are often nearly full-screen and left little space to scroll. I disable this for the case of full-screen elements (our editor is a good example), since scroll won't do anything anyway, so all touches go to orbit. 

UPDATE: I've added a `touch-action` attribute to control the behavior, so the old scroll-swallowing behavior can be achieved with `touch-action='none'`, and side-scrolling for carousels can use `touch-action='pan-x'`. I was hoping to use the actual CSS touch-action and I tried in #1645, but alas I was thwarted by iOS bugs. 

The only important change is the block starting at line 493 in SmoothControls.ts. The rest is dead code removal.

### CODE REVIEW

**Comment by mrdoob** [comment]
@pushmatrix what do you guys think?

**Comment by bldelgado** [comment]
Hey all! We did some user testing around this functionality and ended up coming up with an Active and Inactive state. What we saw, was:

1. Users didn't understand that they needed to move left and right before they could move up and down. The UI to direct them also felt clunky and really had to many steps or times of trial before getting it right.

2. Once users were able to manipulate the 3D model, they found themselves unable to get out of that scroll take over experience and would be frustrated.

3. Hotspots on the page were easy to miss

4. Even having an animation that went left to right, we had users expect to interact with the model by flicking it up and down but would become frustrated when it wouldn't do so or would assume it didn't work or that it was just an "animating image"

**Comment by elalish** [comment]
@bldelgado Thanks for the feedback! Have you tried this branch's version? I'm curious how similar this approach is to yours and if you therefore anticipate it suffering the same problems?

**Comment by mrdoob** [comment]
@bldelgado Were your test with a single model on a page, or with multiple models?

**Comment by bldelgado** [comment]
@elalish I haven't tried the latest, but we did try a version where we locked the Y axis and unlocked it after a certain amount was rotated around the x-axis.

@mrdoob our testing was with a single model on the page. We spent time looking at affordances to denote 3D versus an image and what that "active/play" button would look like.

**Comment by mrdoob** [comment]
While working on [this 3d comic](https://3dcomic.shop/inkbots/s01e01/) today, I discovered that one can achieve this behaviour by doing:

```js
element.style.touchAction = 'pan-y';
```

Compatibility seems surprisingly good:

https://caniuse.com/mdn-css_properties_touch-action_axis-pan

**Comment by elalish** [comment]
@mrdoob That's interesting; it's quite a bit like what I implemented. I just tried your site on my iphone and found it has a bit of delay; I can start dragging the model sideways, but if I too quickly then move down, it snaps back to scrolling. It does seem like using a standard web feature might be better than implementing it myself...

**Pull request merged**
