### PR TITLE
Enable transparencyAsCoverage in Babylon Viewer

### PR DESCRIPTION
**Pull request by bghgary**
### Reference Issue
See https://github.com/KhronosGroup/glTF-Sample-Assets/pull/34#issuecomment-1775665652

### CODE REVIEW

**Comment by elalish** [comment]
Thank you! Is it working? You may want to update the babylon.js version while you're at it; it's probably quite out of date.

**Comment by bghgary** [comment]
No idea. I am not having luck getting it to run yet.

**Comment by bghgary** [comment]
@elalish I am unable to get the `cla/google` to pass since I only use the `users.noreply.github.com` email in my commits which doesn't work apparently. Maybe you can take it further?

**Comment by bghgary** [comment]
I don't know what `full_test_run` is and why it's waiting.

> You may want to update the babylon.js version while you're at it; it's probably quite out of date.

Maybe as a separate PR to limit the changes.

**Comment by elalish** [comment]
Oh, don't worry about `full_test_run` - you're not changing anything in that code anyway. I need to update our CI for contributors. And it looks like @bhouston updated Babylon in #4535, so we should be good.

**Review by elalish — APPROVED** [review]
Thanks!

**Comment by elalish** [comment]
So, our CI does't actually run any renderers besides <model-viewer>. Let's let a few more of @bhouston's PRs land and that should make it easier for you to update goldens.

**Comment by bghgary** [comment]
> that should make it easier for you to update goldens.

Hmm, I don't see any information on this, so I have no idea what you are talking about.

**Comment by elalish** [comment]
#4542

**Comment by bghgary** [comment]
Ok, just tell me what I need to do. I can't even get the `npm run test` to work locally.

**Comment by elalish** [comment]
Okay, if your dev environment isn't working then I'll assume you know how to write Babylon code like this blindly. I'll go ahead and merge it. If @bhouston has any trouble making babylon goldens, he can ping you here or there.

**Comment by bghgary** [comment]
I would definitely prefer for it to work, but let me know if something goes wrong with this change.

**Pull request merged**
