### PR TITLE
Update create-html.ts DOM text reinterpreted as HTML

### PR DESCRIPTION
**Pull request by Shivam7-1**
By using innerText, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML. Always be cautious when dealing with user input or dynamic content to prevent security risks.

### CODE REVIEW

**Comment by Shivam7-1** [comment]
Hi @elalish Could You Please Review This PR 
Regards

**Comment by elalish** [comment]
Have you tested the docs pages with this change to verify nothing has regressed?

**Comment by Shivam7-1** [comment]
Hi @elalish Thanks For Replying 
I think it shouldn't cause any issue 
Regards

**Comment by elalish** [comment]
>I think it shouldn't cause any issue

This kind of sentiment makes me very nervous. Please provide screenshots.

**Comment by Shivam7-1** [comment]
Hi @elalish Thanks For Reviewing 
 It Passes All Test As i check Here Unit test and fidelity test also
Regards 
image
image

**Comment by elalish** [comment]
Sorry, I may have been imprecise - the docs pages don't have automated tests - you have to manually look at them. What I mean is `npm run serve` and look at them to ensure they aren't broken. e.g.
image

**Comment by NeilFraser** [comment]
This PR would break this product since raw HTML would be printed on the user's screen.

**Pull request closed without merging**
