### PR TITLE
Add public API .d.ts file

### LINKED ISSUE #1502: Include TypeScript type definitions on npm package
### Description

I'm using this module on a TypeScript React app through npm and I've noticed that it is missing its type definitions.
More specifically, I'm interested in using the Scene Graph API without having to debug or deep dive into the examples and glTF documentation.

I'm currently using the following:

```typescript
declare global {
  namespace JSX {
    interface IntrinsicElements {
      'model-viewer': ModelViewerJSX & React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> ;
    }
  }
}

interface ModelViewerJSX {
  src: string
  poster?: string
  // ... others
}

interface ModelViewerElement extends Element {
  model: {
    materials: Array<{
      name: string,
      pbrMetallicRoughness: {
        setBaseColorFactor: ((x: [number, number, number, number]) => void),
        setMetallicFactor: ((x: number) => void),
        setRoughnessFactor: ((x: number) => void),

        baseColorTexture: null | {
          texture: {
            source: {
              setURI: ((x: string) => void),
            }
          }
        }
        metallicRoughnessTexture: null | {
          texture: {
            source: {
              setURI: ((x: string) => void),
            }
          }
        }
        // ... others
      }
    }>
  }
}
```

I believe these definitions are probably already inside the `model-viewer` repo, but are not getting exported to `npm`

#### Live Demo

N/A

### Version
- model-viewer: v1.2.1

### Browser Affected
- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS
- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### PR DESCRIPTION
**Pull request by elalish**
Fixes #1502 

It does generate the single file, however it is giant and includes much more than our public API. I'll consider this blocked on https://github.com/Swatinem/rollup-plugin-dts/issues/133 unless a better way can be found.

### CODE REVIEW

**Comment by michaelkochhugobosscom** [comment]
any news about that ?

**Comment by elalish** [comment]
No; can you give some detail of your desired dev process and what you're hoping to do? Most of our users just put MV in as HTML; it'll be helpful to know what TS users are up to. Our library is also published on npm, so it should be possible to import the files from `/lib` instead of the bundle, since those all have `.d.ts` files associated. I'd still like to get a single `d.ts` file that only includes our public API, but I have yet to figure out a good way to do that.

**Comment by Ducki** [comment]
'[…] and what you're hoping to do'
Well, for a start: not getting never ending errors and compilation failures because Typescript doesn't understand what I'm importing and using.
Further: actually using Typescript with the API of the model-viewer (also without getting errors and failing to compile).

**Comment by elalish** [comment]
Closing in favor of #3718

**Pull request closed without merging**
