### PR TITLE
Blender Cycles Fidelity Test

### PR DESCRIPTION
**Pull request by vis-prime**
Fixes / Photos here : https://github.com/google/model-viewer/issues/4482

 This script renders a `exr` file to the output directory.
 Opens it & uses PILLOW to do ACES tonemaping.
 Saves the final png & deletes the exr file.

**The command :**

```
blender -b -P test/renderers/blender-cycles/render.py -- {"scenario": {...}, "outputFile": "..."}
```

**Command breakdown**
- blender is path to the blender executable , How do I mention it in the commit ? ([3.6.4](https://download.blender.org/release/Blender3.6/) or  [4.X.X](https://builder.blender.org/download/daily/) daily build ) 
-  `-b` is for background mode
- `-P` runs the python script
- `test/renderers/blender-cycles/render.py` is the path to the python file
- and last part is the config json ( accessible under `sys.argv[5]` )

**Current settings**
- `128` samples (default: 4096 )
- use `GPU` (default: CPU)
- `Importance sampling/Adaptive Sampling/Noise Threshold` enabled (default: Enabled)
- `OpenImage Denoiser` Enabled (default: Enabled)
- colorspace `Standard` (default: 'AgX' in 4.X & "Filmic" in 3.X)"
 - exports a `temp.exr` (32bit ZIP codec) to the output dir 

_WSL on my windows system does not work on my old system, so npm install didn't work :-(
So I've replicated the changes from the V-Ray commit :-)
and to get outputs, I am running the script directly using the `config.json`_

### CODE REVIEW

**Comment by bhouston** [comment]
@vis-prime amazing!  I'll try it out now.  I think you need to side the Google CLA as mentioned above!  It is super simple to do. :). I think it should use whatever Blender you have installed, so just the default Blender path I think is sufficient.

**Comment by bhouston** [comment]
It may be useful to have a README.md that describes how to set this up?

Are you using Blender directly, I guess you modify PYTHONPATH to point to somewhere inside of Blender, or are you compiling Blender as a Python Module?  I assume as well you have to match the local Python version to Blender's python version, or are you using their python build directly?

This would help me reproduce.

**Comment by vis-prime** [comment]
alright! will do a readme rehearsal here 


1. Ensure you have Blender installed. You can either install the full version of Blender or extract the [zip file](https://download.blender.org/release/Blender3.6/) to a location of your choice. (~350mb)

2. When running the script, provide the path to the Blender executable as the first argument.

3. The entire process utilizes Blender's internal Python module, so there should be no concerns about python version mismatches. 

4. Note that PILLOW is not included in Blender's Python & gets automatically installed within the script.




So in my case with windows and blender 3.6
```
C:/Program Files/Blender Foundation/Blender 3.6/blender 
-b 
-P 
F:/net/model-viewer/packages/render-fidelity-tools/test/renderers/blender-cycles/render.py 
-- {"scenario": 
         {
             "lighting": "...", 
            "dimensions": {"width": 2048, "height": 1536}, 
            "target": {"x": 0, "y": 3.8, "z": 0}, 
            "orbit": {"theta": 0, "phi": 90,
             "radius": 20}, 
             "verticalFoV": 45, 
             "renderSkybox": true, 
             "name": "DirectionalLightTest", 
             "model": "....gltf", 
             "exclude": ["stellar"]
         }, 
         "outputFile": "..._cycles.png"
 }

```
extras

https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html#command-line-launch-index
https://docs.blender.org/manual/en/latest/advanced/command_line/render.html

**Comment by vis-prime** [comment]
Previews

Image order: _Cycles | Model Viewer | Path Tracer_

**Comment by elalish** [comment]
Looking good! Mind signing our CLA and resolving the conflicts? Once these new goldens are uploaded we can look at merging this. Looking at CesiumMan and BrainStem it appears Blender is rendering these at their first animation frame instead of their resting pose - can you fix that in the python?

**Comment by vis-prime** [comment]
CesiumMan model notes

1. This and any models which have rigs/armature can be set into `REST` pose so it's no longer in frame 1 pose.
b4
after


2. This model also has a icosphere mesh ,which automatically loads as `hidden in the viewport` but this mesh is still enabled for rendering so it shows up in the final render

_(left: viewport | center: render output | right: node tree)_ 
hide in viewport

Should I hide this mesh in render too ? or leave it since this is the default behavior ?

**Comment by vis-prime** [comment]
The ones which got fixed
ceeesman
rig simple
foxy

Still messed up, I guess its lost it original position when the frame 1 got applied 
old new

**Comment by vis-prime** [comment]
which one of these is correct ?

```
{
      "name": "blender-cycles",
      "description": "Blender's Cycles render engine",
      "command": {
        "executable": "python3",
        "args": [
          "blender",
          "-b",
          "-P",
          "test/renderers/blender-cycles/render.py"
        ]
      }
    }
 ```
 
 or 
 
 ```
 {
      "name": "blender-cycles",
      "description": "Blender's Cycles render engine",
      "command": {
        "executable": "blender",
        "args": [
          "-b",
          "-P",
          "test/renderers/blender-cycles/render.py"
        ]
      }
    }
 ```

**Comment by elalish** [comment]
Hmm, I'm not sure about "correctness" if they both work, but 

>The entire process utilizes Blender's internal Python module, so there should be no concerns about python version mismatches.

makes me think that the second one is better, since the first might use your random system version of Python?

**Comment by vis-prime** [comment]
I haven't been able to test it with the `npm run update-screenshots` command

`npm install` fails cause WSL does not work _(long story , need to buy a new laptop)_

I've been just loading the `config.json` & running the script directly, so not sure if either of these commands are correct 

@bhouston can you give it a go ?

**Comment by bhouston** [comment]
@vis-prime I will have a look!

**Comment by julienduroure** [comment]
I just fixed the sphere issue.
Should be available in tomorrow's build.

https://github.com/KhronosGroup/glTF-Blender-IO/commit/fc2a7ae81df857cb1b9f19d64245a71f8d075757

The sphere is used for bone/joint shape, and should neither been seen in render

**Comment by bhouston** [comment]
The second method seems the most reasonable, run blender and give it a python script seems simplest.  I may have suggested the first approach, but I think I was wrong earlier.

**Comment by elalish** [comment]
1) Yes
2) Yes
3) Correct, generally we exclude ones that crash or have some problem unrelated to glTF.

**Comment by vis-prime** [comment]
Some changes are coming to GLTF & Principled v2 logic in the coming weeks (blender 4.0 releases in November)

Right now there are some issues with using the daily build (https://github.com/KhronosGroup/glTF-Blender-IO/pull/2014#issuecomment-1752909459)



Is it better to wait for 4.0 release ?
or
Render the Golden's with the old principled bsdf from blender 3.6 and update it later ?

**Comment by elalish** [comment]
I'll defer to @bhouston since he's paying for the work, but since I don't see any particular time rush, I think it might be easier to wait for the 4.0 release.

**Comment by julienduroure** [comment]
> Some crucial changes are coming to GLTF & Principled v2 logic in the coming weeks (blender 4.0 releases in November)

Changed are made. You should be able to get good render with 4.0 beta now.

**Comment by elalish** [comment]
Looking great! I can already see some bugs it's catching in Blender. You'll probably want to wait for some more of @bhouston's PRs to land so that you're updating the right scenarios.

**Comment by elalish** [comment]
Is this ready for review? It's still marked as draft.

**Comment by vis-prime** [comment]
i tried wsl2 , no luck

Only thing i wanted to confirm was to check if blender was getting the full paths as arg and not the relative path (as blender's python env might not have access to it)

blender 4.0 is out !
to install linux `sudo snap install blender --classic`

**Comment by elalish** [comment]
I'm not sure, but I'll let @bhouston guide this one.

**Comment by vis-prime** [comment]
Installed npm packages with WSL2
then ran `npm run update-screenshots khronos-BoomBox blender-cycles` on windows

and after fixing the relative path issue by doing a some path surgery , it still shows the error message but the render output is created correctly !

another note : none of the python print statements or error messages show up on the terminal when running the update-screenshot command 

_(in the video i'm using 12 samples to get the file quickly)_

https://github.com/google/model-viewer/assets/119810373/b6142e00-3a78-46cf-a33e-e9c526387ff0

**Comment by vis-prime** [comment]
on WSL2 
ran the new `npm run render-goldens -- --renderer=blender-cycles -m` command

Image is generated correctly but there's an error at the end which stops the code, (so just ran the command multiple times to get the all the remaining goldens)


Image order : cycles | model-viewer

new

**Comment by elalish** [comment]
Sorry, I kind of lost track of this one. Should I go ahead and merge it? Appears to be complete now?

**Comment by vis-prime** [comment]
I'll just run the command in the latest blender version and let you know..

Can merge after that

**Review by elalish — APPROVED** [review]
Thank you!

**Pull request merged**
