### PR TITLE
Update to three.js r121.1

### LINKED ISSUE #1530: Transparency issue when compress/ optimize the baseColor png file
### Description

The glb assets with transparency in the baseColor map as a compressed/ optimized png. The same asset displayed correctly in BabylonJS Sandbox player, donmccurdy's ThreeJS player, but not in the Model Viewer or, the ThreeJS online editor.

### Version
The test is done online https://modelviewer.dev/editor/ as of September 11th, 2020.

### Browser Affected

- [v ] Chrome

### OS
- [v] Windows

### PR DESCRIPTION
**Pull request by elalish**
Fixes #1530 

FYI @mrdoob Everything's looking good so far.

### CODE REVIEW

**Comment by elalish** [comment]
@donmccurdy @mrdoob I take it back; looks like this broke our 3DOM tests pretty consistently (at least on windows VMs). Sadly I can't repro the problem locally on my macbook. Did anything happen to the CorrelatedSceneGraph?

**Comment by donmccurdy** [comment]
I don't know how CorrelatedSceneGraph works on the model-viewer side, but does it depend on object names somehow? If so, de-duplication of names could be relevant: https://github.com/mrdoob/three.js/pull/16639

**Comment by elalish** [comment]
@donmccurdy Sorry, forgot that was the 3DOM class. It uses `gltf.parser.associations` from the GLTFLoader. I looked through your PR, but it doesn't seem like names should affect it. Are you actually generating new nodes? I also can't imagine how it could be not broken for me locally. It's timing out, which usually means something failed, but maybe it's just really slow?

**Comment by donmccurdy** [comment]
I wouldn't have expected `gltf.parser.associations` to change with this release, or to depend on names generally. Names associated with three.js objects derived from the glTF file will be changed if they conflict. But there wasn't much in GLTFLoader this release, so I'm surprised this is broken.

**Comment by elalish** [comment]
@donmccurdy @mrdoob nevermind, it looks like it's not Three's fault after all. I did an update of npm without updating three.js and found the same error: #1575. Not sure why my dependencies seem to be going crazy...

**Comment by elalish** [comment]
Closing in favor of #1577

**Pull request closed without merging**
