### PR TITLE
Babylon.js renderer: Fixing some models being rendered black

### PR DESCRIPTION
**Pull request by Popov72**
This is a small PR to fix some models that are rendered black with the Babylon.js renderer.

### CODE REVIEW

**Review by elalish — CHANGES_REQUESTED** [review]
Looks good! Can you upload any babylon renders that have changed? Use `npm run update-screenshots babylon`. Also, any trouble signing the CLA?

**Comment by elalish** [comment]
Okay, I rescanned it and it passed, so it looks like whatever you did worked. We have instructions for setting up the project under [WLS2](https://github.com/google/model-viewer#windows-1011-setup) - if that's not working it would be great to know what needs to be updated in our instructions.

Failing that, we can also merge this and I can update the screenshots here in a follow-up.

**Comment by Popov72** [comment]
The problem is with the chrome instance used by pupeeter: it does not support WebGL/WebGL2 and I wasn't able to enable the support.

**Comment by elalish** [comment]
Oh, right, I've actually been running into this problem too - the Chrome 109 update introduced this problem (even on my mac). Okay, I'll merge this and see if I can work around it from here. Thanks!

**Review by elalish — APPROVED** [review]

**Pull request merged**
