### PR TITLE
Ar bug

### PR DESCRIPTION
**Pull request by kenchikuliu**
### Reference Issue

<model-viewer&gt; Scene Graph Worklet>
Uncaught TypeError: modelViewer.model is undefined.

### CODE REVIEW

**Comment by kenchikuliu** [comment]
> ### Reference Issue
> <model-viewer> Scene Graph Worklet>
> Uncaught TypeError: modelViewer.model is undefined.
anyone can tell me how to fix it?

**Comment by elalish** [comment]
@kenchikuliu Did you intend to file a PR? This sounds more like an issue or question. Perhaps you could close this an open an issue? I'm going to need some more specific repro steps in order to help.

**Comment by kenchikuliu** [comment]
[cid:62edf726-a703-45d6-af3d-1c747ef8fcd1]
[cid:3eaff148-c8f1-4abc-aa07-7c352282f8ba]
I use the same code from https://modelviewer.dev/examples/scene-graph.html，but it still cannot work，other ca's
发自 Outlook<http://aka.ms/weboutlook>
________________________________
发件人: Emmett Lalish <notifications@github.com>
发送时间: 2020年7月23日 23:42
收件人: google/model-viewer <model-viewer@noreply.github.com>
抄送: kenchikuliu <kenchikuliu@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [google/model-viewer] Ar bug (#1398)


@kenchikuliu<https://github.com/kenchikuliu> Did you intend to file a PR? This sounds more like an issue or question. Perhaps you could close this an open an issue? I'm going to need some more specific repro steps in order to help.

―

**Comment by elalish** [comment]
@kenchikuliu I'd guess you're trying to use the scene-graph feature with v1.0 of <model-viewer>, but that feature hasn't actually been released yet. You can play with the master version in the meanwhile: 
`<script type="module" src="https://modelviewer.dev/node_modules/@google/model-viewer/dist/model-viewer.min.js></script>`
The v1.1 release should be going out next week with this change.

**Comment by kenchikuliu** [comment]
thxs a lot, now it works great.but new problems come,the 'scene-viewer'mode can not run in my pixel 4. could u give me some advice? thx.
[cid:e9f81f1e-ba88-4848-9a24-9254cecff9fa][cid:ec285136-ecea-430b-9997-d46490ec8a1f]

发自 Outlook<http://aka.ms/weboutlook>
________________________________
发件人: Emmett Lalish <notifications@github.com>
发送时间: 2020年7月24日 22:58
收件人: google/model-viewer <model-viewer@noreply.github.com>
抄送: kenchikuliu <kenchikuliu@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [google/model-viewer] Ar bug (#1398)


Closed #1398<https://github.com/google/model-viewer/pull/1398>.

―

**Comment by elalish** [comment]
@kenchikuliu Please file an [issue](https://github.com/google/model-viewer/issues/new) (instead of a PR) and include the relevant details and I'll notify the SceneViewer team.

**Pull request closed without merging**
