### PR TITLE
turn off tone mapping for unlit models

### PR DESCRIPTION
**Pull request by elalish**
Fixes #3147 
Fixes #3098 
Fixes #2428 

Okay, apparently this was brought up at least  three times; anyway it's now finally fixed: we don't apply tone mapping when all the materials in the model are using the `KHR_materials_unlit` extension. This will allow the RGB colors in the  baseColor texture to show through unchanged in the output render.

### CODE REVIEW

**Review by samaneh-kazemi — APPROVED** [review]

**Comment by mrdoob** [comment]
You could also set `material.toneMapped = false` on unlit materials:
https://threejs.org/docs/?q=material#api/en/materials/Material.toneMapped

**Comment by elalish** [comment]
Ah, that's helpful  to know. So  many ways to set things...

Is there any reason that's not done automatically in GLTFImporter for unlit materials?

**Comment by mrdoob** [comment]
No reason. Is that in the spec?

**Comment by elalish** [comment]
No, the spec doesn't say anything about tone mapping, but it really doesn't make any sense for an unlit material; all anyone wants is for the RGB color to come through un-adulterated.

**Comment by mrdoob** [comment]
I can see pros and cons to both options so I'd prefer to let the GLTF WG decide.

**Comment by mrdoob** [comment]
@donmccurdy Any opinion about this?

**Comment by donmccurdy** [comment]
I'd prefer if GLTFLoader did not change `material.toneMapped` — many engines are likely to do tone mapping in a post-processing stage, rather than in a material shader. We'd be inconsistent with those if we change this.

**Pull request merged**
