### PR TITLE
Add modelviewer link to editor

### PR DESCRIPTION
**Pull request by chrismgeorge**
* Per title

### CODE REVIEW

**Comment by chrismgeorge** [comment]
Screen Shot 2021-01-20 at 10 53 41 AM

**Comment by chrismgeorge** [comment]
tagging @mounirlamouri for visibility

**Comment by elalish** [comment]
Would it be hard to move it above the tabs? Then you could also make it black text on white, which would help separate it from the controls.

**Comment by chrismgeorge** [comment]
> Would it be hard to move it above the tabs? Then you could also make it black text on white, which would help separate it from the controls.

Would you want a border around the box that it, that would align with the editor's edge next to the model-viewer preview?

**Comment by elalish** [comment]
I think that's unnecessary, but let's see how it looks.

**Comment by chrismgeorge** [comment]
Screen Shot 2021-01-20 at 12 17 35 PM

**Comment by elalish** [comment]
Fair enough. How about a light grey background instead of a box? Also, let's up the font size to match the icon.

**Comment by chrismgeorge** [comment]
Screen Shot 2021-01-20 at 12 29 53 PM

??

**Review by elalish — APPROVED** [review]
Thanks!

**Pull request merged**
