### PR TITLE
removed WebGLUtils and old types

### PR DESCRIPTION
**Pull request by elalish**
I want to check if any of this is actually necessary anymore. Better to let three.js figure out which webgl context to use. I also removed a bunch of redundant types since TS types have been updated in the meanwhile.

### CODE REVIEW

**Comment by elalish** [comment]
@mrdoob As far as I can tell WebGLUtils is not necessary anymore and it seems to conflict with the auto-context stuff that three can now do. This code predates me; can you think of any reason this change would be a problem?

**Comment by mrdoob** [comment]
I think this comes from Jordan's old code. I don't think it's needed.

**Comment by mrdoob** [comment]
What do we need `preserveDrawingBuffer: true` for?

**Comment by elalish** [comment]
@mrdoob Thanks! I think I'll probably wait to merge this till after v1.1 anyway, just in case. As for preserveDrawingBuffer, I need to check. I think I had to put it in to work around an offscreenCanvas bug, but since I've now had to turn off offscreenCanvas entirely it may not be necessary.

**Pull request merged**
