### PR TITLE
Attach controls mousemove listener to window

### PR DESCRIPTION
**Pull request by lucadalli**
As per issue #2682, and as a follow-on to #2691, this PR aims to fix the model-viewer's unresponsiveness when the cursor leaves the element's bounds during a mouse interaction.

I would appreciate feedback on the following:
1. Despite the synthetic events used during testing having `{bubbles: true}`, some tests were failing because the `mousemove` events dispatched to the model-viewer element were not triggering the `mousemove` listener on `window`. I fixed this by dispatching the event directly to `window`.
2. [Originally I intended to change the way the cursor styles are applied](https://github.com/google/model-viewer/discussions/2678#discussioncomment-1153581), such that during an interaction, the `grabbing` cursor persists even outside the element's bounds. However, I decided against due to the increased code complexity for a marginal UX improvement. I noticed that other libraries which handle mouse events like Swiper also do not bother with this.
Once the cursor leaves the element's bounds, it is not being paid much attention to anyway as the user is more focused on the model-viewer element itself.

### CODE REVIEW

**Review by elalish — DISMISSED** [review]
Tested and it looks great, on Firefox, Safari, Chrome, Android and iOS. Regarding your two questions, I'm totally satisfied with your solutions. 

However in testing I found a bug related to your previous change (not this PR). On iOS, if you put down one finger, then add a second, you get proper zoom behavior. If  instead you put down both  fingers at once, then it zooms the page  instead of the model. Hopefully a simple fix. Android doesn't have this problem.

**Comment by elalish** [comment]
Looks like this has a conflict now; want to resolve so we can merge this?

**Comment by lucadalli** [comment]
Conflicts with `master` resolved

**Review by elalish — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
