### PR TITLE
R151 redux

### PR DESCRIPTION
**Pull request by elalish**
Re-landing #4186 

Apparently we have to specify that legacy lighting is a bad idea in PBR...

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm... didn't this piece of code warn you?

https://github.com/mrdoob/three.js/blob/8400dc53eff51b434ae965edefa387e7695f9e42/src/renderers/WebGLRenderer.js#L2296-L2308

Or was the fact the fact that the boolean got inverted that confused you?

/cc @donmccurdy

**Comment by mrdoob** [comment]
Oh... Maybe because of the types?

https://github.com/mrdoob/three.js/issues/25744

**Comment by donmccurdy** [comment]
It'd be preferable if the type definitions did something like this, though I imagine it's more trouble to maintain:

```javascript
/**
 * @deprecated Replaced by .useLegacyLights in r151+
 * @default false
 */
physicallyCorrectLights: boolean;

/** @default true */
useLegacyLights: boolean;
```

**Comment by elalish** [comment]
Yeah, I was just going too fast. I had assumed anything called "useLegacy" would default to false.

**Comment by donmccurdy** [comment]
One day... 😢

**Pull request merged**
