### PR TITLE
Added read-only 'duration' property to animations

### PR DESCRIPTION
**Pull request by rhystmills**
This provides a read-only `duration` property which surfaces the duration of the current animation, in the same way that `currentTime` can be accessed.

This PR is derived from a discussion in an [issue](https://github.com/google/model-viewer/issues/1736) on the same topic.

Documentation has also been updated to include a description of the property.

### Reference Issue

Implements Issue #1736

### CODE REVIEW

**Comment by rhystmills** [comment]
As an external dev, I'm not the significance of the failed tests. Could anyone on the core team have a look?

**Comment by elalish** [comment]
Yes, sorry, our tests got rather flaky this week; hopefully sorted out shortly.

**Review by elalish — APPROVED** [review]
Even better if you add a test 🙏. I'm hoping the flakiness is better now; can you pull master and see if that helps?

**Comment by rhystmills** [comment]
> Even better if you add a test 🙏. I'm hoping the flakiness is better now; can you pull master and see if that helps?

Have added some now - tests seem to be doing well!

**Review by elalish — APPROVED** [review]
Thanks! I just prodded it to run the rest of our tests.

**Pull request merged**
