### PR TITLE
Added khornous tests

### PR DESCRIPTION
**Pull request by asemanh**
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TransmissionTest

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TransmissionRoughnessTest

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SpecularTest

### CODE REVIEW

**Review by elalish — APPROVED** [review]
Perfect, thanks! Also, I notice there aren't any scroll bars on these images; did you use your mac, or has something been magically fixed on Linux?

**Comment by asemanh** [comment]
> Perfect, thanks! Also, I notice there aren't any scroll bars on these images; did you use your mac, or has something been magically fixed on Linux?

I used linux. Appologies

**Comment by elalish** [comment]
> I used linux. Appologies I didn't realize I added you while the PR was still on progress

No apologies necessary! That's great, remember how we always used to get weird scroll bars on the images that Linux boxes create? They seem to be gone now, which if it's reliable means one of our package updates may have brought in a fix.

**Comment by asemanh** [comment]
> be gone now, which if it's reliable means one of our package updates may have brought in a fix.

Ah great, the current PR is ready to be reviewed. It covers three model. I'll send a new PR for the others

**Review by elalish — APPROVED** [review]

**Pull request merged**
