### PR TITLE
Fix current time when paused

### LINKED ISSUE #1113: .currentTime is ignored when paused
### Description

We have a couple of usecases where we
- are playing back synced audio with model-viewer animation
- are pausing model-viewer animations at specific points in time
- allow jumping to other points in time, both in play and pause mode

While it's possible to achieve I think I found a bug -
currentTime is ignored when model-viewer is currently paused. This means that to get the behaviour, we currently have to keep model-viewer playing all the time and run a requestAnimationFrame to force it to a specific time. This doesn't feel right and makes this more complicated than it should be.

Note that the Live Demo has some other interesting things we found for audio support - so this is related to
#425, https://github.com/google/model-viewer/issues/483#issuecomment-579449685. 

Also note that autoplay on mobile is handled by browser policy (if you have often pressed play on a website it allows autoplay, if not then not) and is handled in this example by showing a screen overlay.

I started a PR for this but am unsure about some details, see here: #1114 

#### Live Demo
https://glitch.com/edit/#!/chatter-sleet-restaurant

As-is, this shows the broken behaviour - when you pause the audio, you can neither scrub the timeline nor press the buttons to jump to specific seconds, despite modelViewer currentTime being updated (and logged in the console).

If you comment in lines 103..114, this "fixes" it by forcing the currentTime.

### PR DESCRIPTION
**Pull request by elalish**
Fixes #1113 

Thanks @soraryu, I'm taking over your #1114 so we can get it merged for this release. Let me know if any problems remain!

### CODE REVIEW

**Comment by elalish** [comment]
Sorry @soraryu can you sign the CLA again for our googlebot?

**Comment by soraryu** [comment]
@googlebot I consent

**Comment by soraryu** [comment]
@googlebot I consent.

**Comment by soraryu** [comment]
Thanks for taking this over. After trying multiple things (in a Mac VM, in a live Linux, through WSL, ...) without success for running the tests a fresh drive for properly setting up a Linux dev environment arrives today - so in the future I can hopefully actually follow through with my PRs.

**Comment by elalish** [comment]
@soraryu Thanks, and sorry Windows isn't working as a dev environment. I appreciate your dedication!

**Pull request merged**
