### PR TITLE
Added ClearCoatTest model to fidelity tests

### PR DESCRIPTION
**Pull request by augmentedsky**
Added ClearCoatTest model to render-fidelity-tools/test/config.json scenarios

### CODE REVIEW

**Review by elalish — COMMENTED** [review]
Can you please paste in a golden since Github's tool is down?

**Comment by augmentedsky** [comment]
babylon-golden
filament-golden
gltf-sample-viewer-golden
model-viewer-golden

**Comment by augmentedsky** [comment]
Just added them. Any feedback?

**Review by elalish — APPROVED** [review]
Great, thank you!

**Pull request merged**
