### PR TITLE
Bug Fix: Sidebar jumps to incorrect section with uri

### PR DESCRIPTION
**Pull request by chrismgeorge**
Fixed mobile white space & sidebar glitches (image/videos below)

### CODE REVIEW

**Comment by chrismgeorge** [comment]
tagging @mounirlamouri for visibility

**Comment by chrismgeorge** [comment]
Examples, white space issue:
before: https://screenshot.googleplex.com/9Qmw2VwYbX5jR38.png
after: https://screenshot.googleplex.com/52R4FN3kRa9mtWQ.png

**Comment by chrismgeorge** [comment]
Docs, sidebar incorrectly jumps to second section on load sometimes, and glitches when same section is clicked on twice:
Before: https://drive.google.com/file/d/1C9fZRStx8BvC6T33bxt_dXMTc9U_j8kj/view?usp=sharing
After: https://drive.google.com/file/d/1qwYuYAVSb02sOp4if4qB0F0PNlmOyQD9/view?usp=sharing

**Review by elalish — APPROVED** [review]
Much improved, thanks!

**Pull request merged**
