### PR TITLE
fixed permission denial

### LINKED ISSUE #1269: Declining WebXR permission request freezes page
### Description

In the new WebXR flow users are asked for permission to use the camera for AR purposes. Declining that request, however, freezes the entire page instead of letting the user continue exploring the page and trying again at a later point.
Once the permission is declined, it seems after refreshing the page, clicking the "AR" button freezes immediately (without asking again).

#### Live Demo
pfc-writingball.glitch.me

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: latest dist

### PR DESCRIPTION
**Pull request by elalish**
Fixes #1269 

We were failing to properly clean up when the permission to enter webxr was denied.

### CODE REVIEW

**Comment by elalish** [comment]
@sun765 I'm going to start putting you on all my PRs as a reviewer. This is mostly so you can get used to the process. Don't worry about doing a super thorough review, but any questions you have are very much welcome. Mostly I'm just looking for help spotting stupid errors like debug code left in and confusing comments.

**Comment by hybridherbst** [comment]
Thank you for fixing this! One understanding question. 
I know that for e.g. "Camera" permissions in regular apps, the flow is
- app asks user to give permission
- user can accept or decline
- accept: all is good, never asked again
- decline: answer is stored, user is never asked again (this is bad but unfortunately on most Android devices the flow is like this).

How will the flow be for these web permissions? If I declined one of them (e.g. by accident, because I want to go back first, ...), will I have the chance to give permissions again on the next click or will my response be "stuck" and only able to change in some hidden-away submenu?

**Comment by elalish** [comment]
@hybridherbst Yeah, after extensive testing that's how it is here too. You have to click the lock icon on the URL, then site settings and reset permissions. I don't think there's anything I can do about that. Since it comes up when you tap the AR button, hopefully that means most people will be okay granting the permission, since it's pretty clear what it's for.

**Comment by hybridherbst** [comment]
OK, that's very unfortunate. 
Is there any way to detect a "declined permission" on model-viewer side and warn about it / help the user in restoring functionality?

**Comment by elalish** [comment]
@hybridherbst If I understand correctly, I think that is intentionally not exposed by the browser in order to keep sites from badgering users into accepting permissions. We take this quite seriously in Chrome, but I believe the other browsers are similar.

**Comment by hybridherbst** [comment]
I assumed so. From a security standpoint, it's "better safe then sorry" but from an enduser/UX standpoint this is a regression in the WebXR vs SceneViewer implementation.

I added my notes to the other "soft regressions" (is there a better name for "implicit functionality lost with an update"?) to #1270 to keep it out of this closed issue.

**Pull request merged**
