### PR TITLE
fix(model-viewer): update `three` version to correctly allow everything but a major version change #2747

### PR DESCRIPTION
**Pull request by AmitMY**
### Reference Issue
Adresses #2747

### CODE REVIEW

**Comment by donmccurdy** [comment]
I think it'd be common to put `three` in `peerDependencies` and `devDependencies` but omit it from production dependencies. Something like these:

https://github.com/donmccurdy/three-pathfinding/blob/ece8962996f962ea893d9622f77f8e6149eaa676/package.json#L46-L59

https://github.com/pmndrs/react-three-fiber/blob/7b256898c1b0de8ecdae3374b2ebbd1c4b158220/packages/fiber/package.json#L54-L62

**Comment by elalish** [comment]
@donmccurdy Thanks, I've actually been looking for advice on this for some time. That sounds like a reasonable change, but I don't want to take it too lightly. Can you give me a mental model of how to think about the three different kinds of dependencies? Sometimes a three.js version brings in a change that breaks MV and requires an update on our side. What would happen in that case after your proposed change?

**Comment by donmccurdy** [comment]
What I'd aim for would be:

- In `peerDependencies`, give the range of three.js versions that MV intends to be compatible with. `>=0.149.0 <= 1` seems reasonable, I tend to be pretty liberal here. Users will see a warning about the peer dependency if their three.js version is missing or outside the range. 
- In `devDependencies`, give the _exact_ three.js version that you want to use when developing, and testing, within the MV repository. This has no effect on users installing from npm, but would affect builds to a CDN.
- In `dependencies`, omit three.js entirely. Because `dependencies` will override `peerDependencies`, any version specified here would create restrictions (and possible duplicate packages!) that you probably don't want. If the user had their own copy of three.js and the version didn't match `dependencies`, they'll likely end up with two copies in the bundle.

That would probably need to be considered a breaking change, though. Users must install three.js themselves when using npm, whereas three.js comes in automatically with MV on npm now. The benefit of the change is (1) flexibility in the version of three.js supported, and (2) eliminated risk of duplicating three.js in the bundle.

**Comment by elalish** [comment]
Okay, so I guess the main risk is that someone updates their peer dependency to a newer version of three that has a serious breaking change for us and they don't understand why MV seems to be broken (subtly or otherwise). That happens less often now than it used to, but still. If the peer dependency thing is just a warning, I'm tempted to make that version exact too - would that cause other problems?

Also, should I take this same approach to our other dependency, `lit`? Or is there something that makes that a special case? @e111077, do you have opinions here?

**Comment by e111077** [comment]
Lit is interoperable with other versions of Lit and in model-viewer's case, essentially an implementation detail. Lit team's guidance is to simply include it as a normal dep and not a peer dep

**Comment by donmccurdy** [comment]
> If the peer dependency thing is just a warning, I'm tempted to make that version exact too - would that cause other problems?

Does MV have APIs that accept or return three.js objects? Or are the three.js objects just used internally, not in public interfaces? 

For a library-shaped thing (not sure if that describes MV?), an exact version is problematic — it only takes two three.js-related libraries that each require a specific version number before you have a pretty complicated conflict. If I'm using three.js non-trivially elsewhere in the app, I wouldn't want a dependency dictating the version that way.

To be conservative, you could specify r145–r150 or something, and just update the range when necessary. Incrementing the range to r145–r151 would just be a patch release, easy enough.

To be even more conservative, and specify an exact version, I'd recommend using `dependencies` instead, and just accept the risk of duplicating three.js in the bundle.

**Comment by elalish** [comment]
> To be even more conservative, and specify an exact version, I'd recommend using `dependencies` instead, and just accept the risk of duplicating three.js in the bundle.

Yeah, I think this is basically how we arrived where we are. No, we don't have three.js objects as part of our public API, but we touch so many parts of three.js that we often get hit with breaking changes anyway. Most recent was the loss of SpecGloss support, not to mention the whole `TwoPassDoubleSided` thing. Since I only have testing for one version of three.js, I'm a little worried about saying others are fine. 

@AmitMY Regarding your original issue, v3.0 does use three.js r149, so you should be fine if you simply upgrade MV version - we always state what three.js version we're on in the release notes. Is there a reason you prefer to upgrade them independently?

**Comment by AmitMY** [comment]
Currently, I was not using v3.0.0 because of #4090 (which is now fixed).
In my project, I am using three.js independently of `model-viewer` (to do a lot of mathy vector things), and we have a policy that every dependency must be updated to latest unless it is breaking the build/tests. Being "in sync" with MV would require someone to always check your versions, rather than let npm's installation process resolve the packages.

I think that @donmccurdy's solution is the best one:
1. `peerDependencies`: `three=>=0.149.0 <= 1`
2. `devDependencies`: `three=0.149.0`

If this was even a 100kb dependency, I would not bother, but since this is `three`, and is `>1MB`, it is harmful to use it.

Another option is for me to use tree shaking on my three dependency, so MV is not affected, but that would require MV to somehow publically export three, so I can use the installed MV three to interact with the models.

**Comment by elalish** [comment]
> (Another, more difficult option is for me to use tree shaking on my three dependency, so MV is not affected, but that would require MV to somehow publically export three, so I can use the installed MV three to interact with the models.)

Actually, I've wanted to do this for awhile, and I don't think it's too hard. Basically I need another version of our bundle: model-viewer-three.js that would export all of THREE. It will be a little larger since we can't tree shake anything out, but probably not bad. 

Do you at least understand my reasoning above why I'm concerned about mixing and matching with different versions of three?

**Comment by AmitMY** [comment]
I understand your reasoning, and it is true for almost all cases that use peer dependencies, however, this is so costly, that it should be the developer's choice IMO. it is nearly 1MB of bundle increase, which is (at least for me), quite a lot

**Comment by elalish** [comment]
@AmitMY true, but as you said, all you need to do is break your latest-version policy to keep three.js and mv in lockstep. We're generally no more than two versions behind, and usually less. I think for the stability of your project, this is a good idea.

**Comment by elalish** [comment]
@AmitMY Unless I've misunderstood - does putting three in `dependencies` mean you can't share it in your project at all? Or just if your other version doesn't match? If the former, then switching to `peerDependencies` with a strict version number would be fine with me.

**Comment by elalish** [comment]
I'm working on putting out a patch release ideally tomorrow - if we can reach consensus by then, I can include the change.

**Comment by AmitMY** [comment]
To be honest I'm a bit lost.

**Comment by elalish** [comment]
Okay, we've done some testing and it looks like switching to a peer dependency is the right way to go (thanks @e111077 
and @donmccurdy). I'm going to pin the minor three.js version, since that will keep people on what we've tested and can stand behind. But you can still force your way around and use a different non-matching version with `--legacy-peer-deps`, which seems like the right level of warning for using a version of three with potentially breaking changes.

**Comment by AmitMY** [comment]
Thank you, that seems like a good solution to me.
Can close this.

**Comment by elalish** [comment]
Closing in favor of #4135.

**Pull request closed without merging**
